#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-fst
Version  : 0.9.8
Release  : 38
URL      : https://cran.r-project.org/src/contrib/fst_0.9.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/fst_0.9.8.tar.gz
Summary  : Lightning Fast Serialization of Data Frames
Group    : Development/Tools
License  : AGPL-3.0
Requires: R-fst-lib = %{version}-%{release}
Requires: R-fst-license = %{version}-%{release}
Requires: R-Rcpp
Requires: R-fstcore
BuildRequires : R-Rcpp
BuildRequires : R-data.table
BuildRequires : R-fstcore
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
'fst' format allows for full random access of stored data and a wide range of compression
    settings using the LZ4 and ZSTD compressors.

%package lib
Summary: lib components for the R-fst package.
Group: Libraries
Requires: R-fst-license = %{version}-%{release}

%description lib
lib components for the R-fst package.


%package license
Summary: license components for the R-fst package.
Group: Default

%description license
license components for the R-fst package.


%prep
%setup -q -n fst
pushd ..
cp -a fst buildavx2
popd
pushd ..
cp -a fst buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737144664

%install
export SOURCE_DATE_EPOCH=1737144664
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-fst
cp %{_builddir}/fst/LICENSE %{buildroot}/usr/share/package-licenses/R-fst/944fd06c8ee33187c425050cd74c5b81acf9edf7 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/fst/DESCRIPTION
/usr/lib64/R/library/fst/INDEX
/usr/lib64/R/library/fst/LICENSE
/usr/lib64/R/library/fst/Meta/Rd.rds
/usr/lib64/R/library/fst/Meta/features.rds
/usr/lib64/R/library/fst/Meta/hsearch.rds
/usr/lib64/R/library/fst/Meta/links.rds
/usr/lib64/R/library/fst/Meta/nsInfo.rds
/usr/lib64/R/library/fst/Meta/package.rds
/usr/lib64/R/library/fst/NAMESPACE
/usr/lib64/R/library/fst/R/fst
/usr/lib64/R/library/fst/R/fst.rdb
/usr/lib64/R/library/fst/R/fst.rdx
/usr/lib64/R/library/fst/WORDLIST
/usr/lib64/R/library/fst/help/AnIndex
/usr/lib64/R/library/fst/help/aliases.rds
/usr/lib64/R/library/fst/help/fst.rdb
/usr/lib64/R/library/fst/help/fst.rdx
/usr/lib64/R/library/fst/help/paths.rds
/usr/lib64/R/library/fst/html/00Index.html
/usr/lib64/R/library/fst/html/R.css
/usr/lib64/R/library/fst/tests/testthat.R
/usr/lib64/R/library/fst/tests/testthat/FactorStore/data1.fst
/usr/lib64/R/library/fst/tests/testthat/bla.fst
/usr/lib64/R/library/fst/tests/testthat/datasets/legacy.fst
/usr/lib64/R/library/fst/tests/testthat/datasets/legacy.rds
/usr/lib64/R/library/fst/tests/testthat/datasets/utf8.csv
/usr/lib64/R/library/fst/tests/testthat/helper_fstwrite.R
/usr/lib64/R/library/fst/tests/testthat/keyedTable.rds
/usr/lib64/R/library/fst/tests/testthat/test_access.R
/usr/lib64/R/library/fst/tests/testthat/test_bigvector.R
/usr/lib64/R/library/fst/tests/testthat/test_compress.R
/usr/lib64/R/library/fst/tests/testthat/test_date.R
/usr/lib64/R/library/fst/tests/testthat/test_encoding.R
/usr/lib64/R/library/fst/tests/testthat/test_factor.R
/usr/lib64/R/library/fst/tests/testthat/test_fst.R
/usr/lib64/R/library/fst/tests/testthat/test_fst_table.R
/usr/lib64/R/library/fst/tests/testthat/test_integer64.R
/usr/lib64/R/library/fst/tests/testthat/test_interface.R
/usr/lib64/R/library/fst/tests/testthat/test_keys.R
/usr/lib64/R/library/fst/tests/testthat/test_legacy.R
/usr/lib64/R/library/fst/tests/testthat/test_lintr.R
/usr/lib64/R/library/fst/tests/testthat/test_meta.R
/usr/lib64/R/library/fst/tests/testthat/test_nanotime.R
/usr/lib64/R/library/fst/tests/testthat/test_omp.R
/usr/lib64/R/library/fst/tests/testthat/test_rbind.R
/usr/lib64/R/library/fst/tests/testthat/test_roundtrip.R
/usr/lib64/R/library/fst/tests/testthat/test_special_tables.R
/usr/lib64/R/library/fst/tests/testthat/test_time.R
/usr/lib64/R/library/fst/tests/testthat/testdata/zero_column.fst
/usr/lib64/R/library/fst/tests/testthat/testdata/zero_row.fst

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/fst/libs/fst.so
/V4/usr/lib64/R/library/fst/libs/fst.so
/usr/lib64/R/library/fst/libs/fst.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-fst/944fd06c8ee33187c425050cd74c5b81acf9edf7
